# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd8adad4d0779637f6464021fc81cf046e973709265b53bc106896516a18c506e83c4a16cc19c3e2096cac7a5d3b74e195625e518cd5f2c29df94a56728a5396

test:
  secret_key_base: 124679a6759587fc49035d01af38f822ee3ccf2237aff9ac07125c4c8f7a6f61c92fd9392833e5de5dc18019095f7b80f2249d7640abe9913afb97cbf2f1ff6c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
